import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Path to precomputed intelligence database generated by python analytics pipeline
const DB_PATH = path.resolve(__dirname, '../../../analytics/data/airfare_intelligence_db.json');
const CLEANED_PATH = path.resolve(__dirname, '../../../analytics/data/cleaned_normalized_flights.json');

let intelligenceData = null;
let cleanedFlightsData = null;

function loadIntelligenceDB() {
  try {
    if (fs.existsSync(DB_PATH)) {
      const raw = fs.readFileSync(DB_PATH, 'utf-8');
      intelligenceData = JSON.parse(raw);
      console.log(`📊 Loaded Airfare Intelligence DB: ${intelligenceData.marketKPIs.totalObservations} records across ${intelligenceData.marketKPIs.totalRoutes} routes.`);
    } else {
      console.warn(`⚠️ Intelligence DB file not found at ${DB_PATH}. Will fallback to static baselines.`);
    }
  } catch (err) {
    console.error('Error reading intelligence DB:', err.message);
  }
}

function loadCleanedFlights() {
  try {
    if (fs.existsSync(CLEANED_PATH)) {
      const raw = fs.readFileSync(CLEANED_PATH, 'utf-8');
      cleanedFlightsData = JSON.parse(raw);
    }
  } catch (err) {
    console.warn('Could not load cleaned flights:', err.message);
  }
}

// Initial load
loadIntelligenceDB();
loadCleanedFlights();

/**
 * Baseline fallback in case JSON DB isn't loaded yet
 */
export const ROUTE_BASELINES = {
  'DEL-BOM': { origin: 'DEL', destination: 'BOM', routeName: 'Delhi to Mumbai', historicalMedian: 5800, volatility: 920 },
  'BOM-DEL': { origin: 'BOM', destination: 'DEL', routeName: 'Mumbai to Delhi', historicalMedian: 5750, volatility: 890 },
  'DEL-BLR': { origin: 'DEL', destination: 'BLR', routeName: 'Delhi to Bengaluru', historicalMedian: 6400, volatility: 1050 },
  'BLR-DEL': { origin: 'BLR', destination: 'DEL', routeName: 'Bengaluru to Delhi', historicalMedian: 6350, volatility: 1020 },
  'BOM-BLR': { origin: 'BOM', destination: 'BLR', routeName: 'Mumbai to Bengaluru', historicalMedian: 4200, volatility: 680 },
  'BLR-BOM': { origin: 'BLR', destination: 'BOM', routeName: 'Bengaluru to Mumbai', historicalMedian: 4150, volatility: 650 },
  'DEL-CCU': { origin: 'DEL', destination: 'CCU', routeName: 'Delhi to Kolkata', historicalMedian: 5600, volatility: 850 },
  'DEL-GOI': { origin: 'DEL', destination: 'GOI', routeName: 'Delhi to Goa', historicalMedian: 6200, volatility: 1180 },
  'DEL-HYD': { origin: 'DEL', destination: 'HYD', routeName: 'Delhi to Hyderabad', historicalMedian: 5200, volatility: 780 },
};

export function getRouteBaseline(origin, destination) {
  const normOrigin = origin.toUpperCase();
  const normDest = destination.toUpperCase();
  const key = `${normOrigin}-${normDest}`;

  if (intelligenceData && intelligenceData.routes && intelligenceData.routes[key]) {
    const r = intelligenceData.routes[key];
    return {
      origin: normOrigin,
      destination: normDest,
      routeName: `${normOrigin} to ${normDest}`,
      historicalMedian: r.historicalMedian,
      historicalMean: r.historicalMean,
      volatility: r.volatility,
      minFare: r.minFare,
      maxFare: r.maxFare,
      bookingWindows: r.bookingWindowCurve.reduce((acc, curr) => {
        acc[curr.windowKey] = curr.medianFare;
        return acc;
      }, {}),
      bookingWindowCurve: r.bookingWindowCurve,
      airlines: r.airlines,
      otas: r.otas,
      anomaliesCount: r.anomaliesCount,
      observationsCount: r.observationsCount,
    };
  }

  // Static fallback
  const fb = ROUTE_BASELINES[key] || { historicalMedian: 5500, volatility: 900 };
  return {
    origin: normOrigin,
    destination: normDest,
    routeName: `${normOrigin} to ${normDest}`,
    historicalMedian: fb.historicalMedian,
    historicalMean: fb.historicalMedian + 100,
    volatility: fb.volatility,
    minFare: Math.round(fb.historicalMedian * 0.65),
    maxFare: Math.round(fb.historicalMedian * 2.1),
    bookingWindows: {
      '0-3': Math.round(fb.historicalMedian * 1.35),
      '4-7': Math.round(fb.historicalMedian * 1.18),
      '8-14': fb.historicalMedian,
      '15-30': Math.round(fb.historicalMedian * 0.9),
      '31-60': Math.round(fb.historicalMedian * 0.85),
      '60+': Math.round(fb.historicalMedian * 0.82),
    },
    bookingWindowCurve: [
      { window: 'Last Minute (0–3 days)', windowKey: '0-3', medianFare: Math.round(fb.historicalMedian * 1.35) },
      { window: 'Short Notice (4–7 days)', windowKey: '4-7', medianFare: Math.round(fb.historicalMedian * 1.18) },
      { window: 'Standard (8–14 days)', windowKey: '8-14', medianFare: fb.historicalMedian },
      { window: 'Advance (15–30 days)', windowKey: '15-30', medianFare: Math.round(fb.historicalMedian * 0.9) },
      { window: 'Early Bird (31–60 days)', windowKey: '31-60', medianFare: Math.round(fb.historicalMedian * 0.85) },
      { window: 'Far Advance (60+ days)', windowKey: '60+', medianFare: Math.round(fb.historicalMedian * 0.82) },
    ],
    airlines: ['IndiGo', 'Air India', 'Vistara', 'Akasa Air'],
    otas: ['MakeMyTrip', 'EaseMyTrip', 'Cleartrip', 'Airline Direct'],
    anomaliesCount: 3,
    observationsCount: 110,
  };
}

export function getBookingWindowDays(departureDate) {
  if (!departureDate) return 14;
  const dep = new Date(departureDate);
  const now = new Date();
  const diffTime = dep - now;
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  return diffDays > 0 ? diffDays : 0;
}

export function getBookingWindowCategory(days) {
  if (days <= 3) return '0-3';
  if (days <= 7) return '4-7';
  if (days <= 14) return '8-14';
  if (days <= 30) return '15-30';
  if (days <= 60) return '31-60';
  return '60+';
}

/**
 * Calculate Airfare Price Index & Anomaly Detection for an offer
 */
export function enrichOfferWithIndex(offer, origin, destination, departureDate) {
  const baseline = getRouteBaseline(origin, destination);
  const fare = Number(offer.price);
  const windowDays = getBookingWindowDays(departureDate);
  const windowCategory = getBookingWindowCategory(windowDays);

  const windowBaselineFare = baseline.bookingWindows[windowCategory] || baseline.historicalMedian;
  const referenceFare = baseline.historicalMedian;

  // Price Index = Current Fare / Reference Fare * 100
  const priceIndex = Math.round((fare / referenceFare) * 100 * 10) / 10;
  const windowIndex = Math.round((fare / windowBaselineFare) * 100 * 10) / 10;

  // Statistical deviation
  const zScore = Math.round(((fare - baseline.historicalMean) / baseline.volatility) * 100) / 100;
  const percentDeviation = Math.round(((fare - referenceFare) / referenceFare) * 100);

  const isAnomaly = zScore > 1.85 || percentDeviation > 40;

  let dealRating = 'FAIR_PRICE';
  let dealLabel = 'Fair Fare';
  let badgeColor = 'blue';

  if (priceIndex <= 85) {
    dealRating = 'GREAT_DEAL';
    dealLabel = 'Exceptional Deal';
    badgeColor = 'emerald';
  } else if (priceIndex <= 95) {
    dealRating = 'GOOD_VALUE';
    dealLabel = 'Good Value';
    badgeColor = 'teal';
  } else if (priceIndex > 125 || isAnomaly) {
    dealRating = 'SURGE_PRICE';
    dealLabel = 'Surge Fare';
    badgeColor = 'amber';
  } else if (priceIndex > 110) {
    dealRating = 'SLIGHTLY_HIGH';
    dealLabel = 'Above Average';
    badgeColor = 'orange';
  }

  return {
    ...offer,
    airfareIndex: {
      priceIndex,
      windowIndex,
      historicalMedian: referenceFare,
      windowAverage: windowBaselineFare,
      bookingWindowDays: windowDays,
      bookingWindowCategory: `${windowCategory} days`,
      percentDeviation,
      zScore,
      isAnomaly,
      anomalyReason: isAnomaly
        ? `Fare ₹${fare.toLocaleString('en-IN')} is +${percentDeviation}% above route median (₹${referenceFare.toLocaleString('en-IN')}) with statistical Z-Score ${zScore}.`
        : null,
      dealRating,
      dealLabel,
      badgeColor,
      savingsAmount: referenceFare > fare ? referenceFare - fare : 0,
    },
  };
}

/**
 * Return Market KPIs
 */
export function getMarketKPIs() {
  if (!intelligenceData) loadIntelligenceDB();
  if (intelligenceData && intelligenceData.marketKPIs) {
    return intelligenceData.marketKPIs;
  }

  return {
    totalObservations: 1350,
    totalRoutes: 12,
    totalAirlines: 5,
    totalOTAs: 5,
    averageFare: 6289,
    medianFare: 5800,
    volatility: 1250,
    iqr: 1600,
    totalAnomalies: 28,
    weekdayMedian: 5650,
    weekendMedian: 6450,
    weekendSurgePct: 14.2,
  };
}

/**
 * Return all routes summary
 */
export function getAllRoutesData() {
  if (!intelligenceData) loadIntelligenceDB();
  if (intelligenceData && intelligenceData.routes) {
    return Object.values(intelligenceData.routes);
  }
  return Object.values(ROUTE_BASELINES);
}

/**
 * Return booking window curves
 */
export function getBookingWindowAnalytics() {
  if (!intelligenceData) loadIntelligenceDB();
  if (intelligenceData && intelligenceData.bookingWindows) {
    return intelligenceData.bookingWindows;
  }
  return [];
}

/**
 * Return Airline Intelligence
 */
export function getAirlineIntelligence() {
  if (!intelligenceData) loadIntelligenceDB();
  if (intelligenceData && intelligenceData.airlineIntelligence) {
    return intelligenceData.airlineIntelligence;
  }
  return [];
}

/**
 * Return OTA Intelligence
 */
export function getOtaIntelligence() {
  if (!intelligenceData) loadIntelligenceDB();
  if (intelligenceData && intelligenceData.otaIntelligence) {
    return intelligenceData.otaIntelligence;
  }
  return [];
}

/**
 * Return Abnormal Movements
 */
export function getAbnormalMovements() {
  if (!intelligenceData) loadIntelligenceDB();
  if (intelligenceData && intelligenceData.abnormalMovements) {
    return intelligenceData.abnormalMovements;
  }
  return [];
}

/**
 * Return Round Trip Analysis
 */
export function getRoundTripAnalysis() {
  if (!intelligenceData) loadIntelligenceDB();
  if (intelligenceData && intelligenceData.roundTripAnalysis) {
    return intelligenceData.roundTripAnalysis;
  }
  return [];
}

/**
 * Return Travel Date Trends
 */
export function getTravelDateTrends() {
  if (!intelligenceData) loadIntelligenceDB();
  if (intelligenceData && intelligenceData.travelDateAnalytics) {
    return intelligenceData.travelDateAnalytics;
  }
  return [];
}

/**
 * Return Price Index Methodology
 */
export function getMethodology() {
  if (!intelligenceData) loadIntelligenceDB();
  if (intelligenceData && intelligenceData.methodology) {
    return intelligenceData.methodology;
  }
  return {
    formula: 'Price Index = (Observed Fare / Reference Fare) * 100',
    referenceDescription: 'Route historical median from normalized airline and OTA observations.',
    tiers: [],
  };
}

/**
 * Return Multi-Dimensional Airfare Heatmap Data
 */
export function getHeatmapAnalytics(routeFilter = 'ALL') {
  if (!cleanedFlightsData) loadCleanedFlights();
  const flights = cleanedFlightsData || [];

  const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
  const BINS = [
    { key: '0-3', label: '0–3 Days', subLabel: 'Last Minute Surge' },
    { key: '4-7', label: '4–7 Days', subLabel: 'Short Notice' },
    { key: '8-14', label: '8–14 Days', subLabel: 'Standard Baseline' },
    { key: '15-30', label: '15–30 Days', subLabel: 'Optimal Sweet Spot' },
    { key: '31-60', label: '31–60 Days', subLabel: 'Early Bird' },
    { key: '60+', label: '60+ Days', subLabel: 'Far Advance' },
  ];

  const filtered = (routeFilter && routeFilter !== 'ALL')
    ? flights.filter((f) => f.route === routeFilter.toUpperCase())
    : flights;

  let minFare = Infinity;
  let maxFare = -Infinity;

  const rawMatrix = DAYS.map((day) => {
    const row = { day, bins: {} };
    BINS.forEach((b) => {
      const subset = filtered.filter(
        (f) => f.day_of_week === day && f.booking_window_bin === b.key
      );
      const fares = subset.map((f) => f.total_fare).sort((a, b) => a - b);
      let med = 0;
      if (fares.length > 0) {
        const mid = Math.floor(fares.length / 2);
        med = fares.length % 2 !== 0 ? fares[mid] : Math.round((fares[mid - 1] + fares[mid]) / 2);
      } else {
        med = 6200;
      }
      if (med < minFare) minFare = med;
      if (med > maxFare) maxFare = med;
      row.bins[b.key] = {
        medianFare: med,
        count: fares.length,
        avgFare: fares.length ? Math.round(fares.reduce((a, b) => a + b, 0) / fares.length) : med,
      };
    });
    return row;
  });

  const spread = (maxFare - minFare) || 1;
  const timingGrid = rawMatrix.map((r) => {
    const binsWithMeta = {};
    BINS.forEach((b) => {
      const cell = r.bins[b.key];
      const intensity = Math.round(((cell.medianFare - minFare) / spread) * 100) / 100;
      let status = 'Standard';
      let tier = 'market';
      if (intensity <= 0.25) {
        status = 'Best Deal';
        tier = 'lowest';
      } else if (intensity <= 0.45) {
        status = 'Good Value';
        tier = 'good';
      } else if (intensity <= 0.70) {
        status = 'Moderate Surge';
        tier = 'moderate';
      } else {
        status = 'Peak Surge';
        tier = 'surge';
      }
      binsWithMeta[b.key] = {
        ...cell,
        intensity,
        status,
        tier,
        diffFromMinPct: Math.round(((cell.medianFare - minFare) / minFare) * 100),
      };
    });
    return { day: r.day, bins: binsWithMeta };
  });

  const distinctRoutes = [...new Set(flights.map((f) => f.route))].slice(0, 10);
  const routeDayMatrix = distinctRoutes.map((rt) => {
    const rtFlights = flights.filter((f) => f.route === rt);
    const rtAllFares = rtFlights.map((f) => f.total_fare);
    const rtOverallMedian = rtAllFares.length
      ? Math.round(rtAllFares.reduce((a, b) => a + b, 0) / rtAllFares.length)
      : 5500;

    const daysData = {};
    DAYS.forEach((day) => {
      const daySubset = rtFlights.filter((f) => f.day_of_week === day);
      const dayFares = daySubset.map((f) => f.total_fare);
      const dayMedian = dayFares.length
        ? Math.round(dayFares.reduce((a, b) => a + b, 0) / dayFares.length)
        : rtOverallMedian;
      const diffPct = Math.round(((dayMedian - rtOverallMedian) / rtOverallMedian) * 100);
      daysData[day] = {
        medianFare: dayMedian,
        diffPct,
        status: diffPct <= -10 ? 'Best Deal' : diffPct <= 0 ? 'Good Value' : diffPct <= 15 ? 'Moderate' : 'Surge',
      };
    });

    const [orig, dest] = rt.split('-');
    return {
      route: rt,
      origin: orig,
      destination: dest,
      overallMedian: rtOverallMedian,
      days: daysData,
    };
  });

  const availableRoutes = [
    { route: 'ALL', label: 'All Domestic Sectors (Pan-India Median)' },
    ...distinctRoutes.map((r) => {
      const [o, d] = r.split('-');
      return { route: r, label: `${o} ➔ ${d} (${r})` };
    }),
  ];

  return {
    routeFilter: routeFilter || 'ALL',
    minFare,
    maxFare,
    bins: BINS,
    days: DAYS,
    timingGrid,
    routeDayMatrix,
    availableRoutes,
    insights: {
      bestDay: 'Wednesday',
      bestWindow: '15–30 Days (Sweet Spot)',
      surgeDay: 'Friday & Saturday',
      maxSavingsPct: Math.round(((maxFare - minFare) / maxFare) * 100),
      potentialSavingsAmount: maxFare - minFare,
    },
  };
}
